#!/bin/zsh

#alias ls="ls++"

# Git alias
alias gst="git status"
alias ga="git add"
alias gc="git commit"

# Yaourt
alias yu="yaourt -Syyu $1"
alias ys="yaourt -S $1"
alias yss="yaourt -Ss $1"
alias yqs="yaourt -Qs $1"
alias yrm="yaourt -Rns $1"

# Copy file text to clipboard
alias clip="xclip -sel clip < $1"

# Docker Containers
alias ion="docker run -ti --rm --privileged -v $PWD:/project:rw -p 8100:8100 -p 35729:35729 -p 53703:53703 ionic3"
